### ISSUE TITLE
Aborted (core dumped) when writing more than 512 bytes

### ISSUE THREAD

**Issue by Krabbens** [kubsnn/TCP-Chat#3]
## Description
While using the "sendto" command, the client unexpectedly experienced a core dump. This issue seems to be triggered specifically after sending 666 "a" characters. The behavior was consistent during multiple tests. 

## Steps to Reproduce
1. Execute the "sendto" command.
2. Send 666 "a" characters as the input

## Expected Behavior
The client should not experience a core dump, regardless of the input.

## Actual Behavior
The client encountered a core dump, leading to an unexpected termination of the process.

## Environment
- Operating system [OpenSuse]
- Compiler [GCC 13.2.1]

**Comment by kubsnn** [comment]
#4 Fixed.
